[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  # Configures Next.js to omit heavy trace files when not needed or optimize for Netlify functions
  NEXT_DISABLE_SOURCEMAPS = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
